//
// Copyright (c) 2025 and Confidential to Eric Ford Consulting All rights reserved.
//

import SwiftUI

extension BattleView {
    @ViewBuilder
    var howToPlayOverlay: some View {
        if viewModel.showHowToPlay {
            ZStack {
                Color(.white)
                VStack {
                    HStack {
                        Spacer()
                        Button(
                            action: { viewModel.showHowToPlay = false },
                            label: { Image(systemName: "x.circle") }
                        )
                    }.padding()
                    ScrollView {
                        VStack {
                            Text("Movement")
                                .font(.system(size: 24))
                                .fontWeight(.heavy)
                                .padding(.bottom, 10)
                            Text("Piece are maps of their movement capabilities. They are made up of prongs.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("Star")
                            Text("When you tap a piece, its legal moves get highlighted.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("StarSelected")
                            Text("The piece above, called a star, has short prongs, which allow a move of one square in the direction the prong is pointing. Pieces can also have long prongs. Here is a rook:")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("Rook")
                            Text("Long prongs can slide in the direction they are pointing until they hit an obstruction.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("RookWithBlocks")
                            Text("The rook can't move onto the square of the star above it since they are on the same team. It can move to either of the blue pieces' squares, but not past them. The last obstruction is the edge of the board on the west (left) side.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Text(" ")
                            Text("Then there are the knights.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("Knight")
                            Text("Knights move in an L shape, 2 squares north south east or west, then one square sideways from that.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("KnightMoves")
                            Text("Knights can jump over other pieces. Here's a surrounded knight:")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("KnightSurrounded")
                            Text("None of those pieces stop the knight from moving.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("KnightCanStillJump")
                            Text("Lastly we also have fat prongs. The king has fat prongs:")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("King")
                            Text("The fat prongs don't affect movement. The king moves the same as a star.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("KingSelected")
                            Text("The fat prongs affect wounding, which is the next topic:")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Text("Wounding")
                                .font(.system(size: 24))
                                .fontWeight(.heavy)
                                .padding(.bottom, 10)
                            Text("When a piece moves onto the square occupied by an enemy, then enemy is captured UNLESS… it has an opposing prong facing directly into the attack.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("StarAndBishop")
                            Text("Here the star can capture the bishop, since the bishop doesn't have a prong pointing directly at the star.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Text("The defending prong must be as strong as the attacker. So a long prong attacking a short prong still gets to capture the piece.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("BishopCapturesStar")
                            Text("Here the bishop can capture the star since the bishop's prong is longer.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Text("Here the bishops' prongs are of equal strength:")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("BishopCanWoundBishop")
                            Text("When prongs are of equal strength, the attacker removes the defender's prong.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("BishopAfterWounding")
                            Text("Once that prong is removed, the bishop can't move in that direction.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Text("If the attacking prong is weaker than the defending prong, the defending prong gets shortened.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("StarCanWoundBishop")
                            Text("Then, after the bishop gets wounded:")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Image("StarWoundsBishop")
                            Text("Now the prong is short instead of long; the bishop can only move one square at a time in that direction.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Text("Rotation")
                                .font(.system(size: 24))
                                .fontWeight(.heavy)
                                .padding(.bottom, 10)
                            Text("Once a piece has been wounded, it is allowed to be rotated, which takes up that players turn the way any other move would. There are Rotate Left and Rotate Right buttons which are enabled when you select a wounded piece.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                            Text("Winning the Game")
                                .font(.system(size: 24))
                                .fontWeight(.heavy)
                                .padding(.bottom, 10)
                            Text("You must capture every enemy piece to win. Note that Boot Camp will take you through several levels before the game ends.")
                                .multilineTextAlignment(.center)
                                .padding(.bottom, 10)
                                .padding([.leading, .trailing], 20)
                        }
                    }
                }
            }
        }
    }
}
